travis:
  secure:
    BINSTAR_TOKEN: Sr5GpGVLQoZ5nODd98ZfPeOzUqtKgwKgoW9U9fzlVPFfWr0R1U7pstA/crz6ssRtC6/0pW0oaVn+RzreZ9a9J/uyVwPIyjIgl9PiGAHQfxgOJ1PcfCTC1gA7TQYms3mNQZsnNsQKxjxbWcbL5Fi9J31vsdT1IP1/iBGHTEDqxuVPrjegOAFBOncIrsbEjtqXU87BOqbG/EGSKCitbENsRK5N0U9pseNlk8K3Bpd6r0pJveCZCLthMJnPVDzhYge5ecljLwrAg5PwbT7H5qEAOuIeW0CMeR0r3flbTsm8SveFGjv/iS3oeChFQ9aYX0WuoEKQU3M/RVBpzHQblTHUlOT2tJztXi3xj6jNdo5T0o74Hm2QoEFG6BgTErvQcUuX+L77A+sbOJ4zcLJOvU2s0xZXJrB37f8vOWeaxJU1llc6gkDTEslqOUKCZE+4n1qmduFaI73RWhPT7sAue6+0ZVa8K0fRZ26tac2I0C1oKLX0c9cF482qy+qxJ3JxexxDT6bQPTNaMyU0pi44JDvBK9ZJWeXx36DoFiaQe/L7kj96KXd3GOfqF8vh43T+ZzQy3oODqT2DakVayf5AyZSCsggAkOuBPyHzTXHkSTwGyAicj4XLYdcb5b+hIEz0jbJXurZhuVKwCPAffhX0RomaPjXFm03AdTZ64p0SEs4fjDM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
