travis:
  secure:
    BINSTAR_TOKEN: ADWezQSx5Ul+eRn1nqPDPWtnzWee3hTBpNwpQqhaPFutkNyqKnRvcBCbttTaU6gYIWOeZl5IQxCAVlLh+Xv3iLmPgzboEA2u6eptrjY/sr7ytcP7bhFUNX9Fvv6zUaSd/W4byP09wkvBksXFGbSxo4n8kGnaiPvUS0WME+jTKcOmhSWMmtW/Hcd0zOnDCUE5CikWnJiKnnisvdj0M7jkraqbJTmyNEHu1I6biYNtoeOVOaTIidTvh67p05bk86qVOERUfjk4JYr7SDdoOdHx3npXujE1cMoHhqVs8+ktwc2UfgeRxB3Vo9+lPnA/Q86b0cYv5Sv9Xb9+wLDC02T7RUI/J10646UgkqBCzZT+j9hszgwZErPY0Yz9/Vy8ruDpNLhQEYATlvLDepTxOq4yPRhAuMY2YnsdzBzU0VDiuo0ZhI5yx0+XiPyiRHIiiI6SkpZ3eTGWAFpTQYhRIf1swPdZ+NMYNiZ3ne/gMMkh9ovX5+SFSgcdxh0l7W+/Ri5H7w9auM2uP/ev6PCpFV7Jk6PKVC1sqyBYI9GJfaUF/xpFOiunVhXJ9dHYWM+3iqk7prKrZuL6NM1xhrdWavwjOcFmZyEhx1VL7o6o+uCDJO2dszcA65SUUz4rl67pGBeI5FiIYYcroE0COKvEeWUOgKIwH38+ui7T1ECr2yniJmA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
